name: Code Check # название

on: [push, pull_request] # запускать при любом пуше в любую ветку и при создании пулл реквеста

jobs: # то что делает пайплайн
  check_html: # название задачи
    runs-on: ubuntu-latest # запуск на ласт версии убунту

    steps: # последовательность шагов
      # 1: получать код из репозитория
      - name: checkout code
        uses: actions/checkout@v4 # загрузка кода 

      # 2: установка Node.js для проверки
      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3: проверка html с помощью html-profer
      - name: check html links
        uses: actionshub/html-proofer@main
        with:
          directory: "./"
          arguments: "--disable-external --check-html"