name: Code Check # название

on: [push, pull_request] # запускать при любом пуше в любую ветку и при создании пулл реквеста

jobs: # то что делает пайплайн
  check_html: # название задачи
    runs-on: ubuntu-latest # запуск на ласт версии убунту

    steps: # последовательность шагов
      # 1: получать код из репозитория
      - name: Checkout code
        uses: actions/checkout@v4 # загрузка кода 

      # 2: установка Node.js для проверки
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3: проверка html с помощью html-proofer
      - name: Setup HTMLProofer
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full
          sudo gem install html-proofer

      - name: Run HTMLProofer
        run: |
          htmlproofer . --check-html --disable-external --allow-hash-href