name: Code Check # название

on: [push, pull_request] # запускать при любом пуше в любую ветку и при создании пулл реквеста

jobs: # то что делает пайплайн
  check_html: # название задачи
    runs-on: ubuntu-latest # запуск на ласт версии убунту

    steps: # последовательность шагов
      # 1: получать код из репозитория
      - name: Checkout code
        uses: actions/checkout@v4 # загрузка кода 

      # 2: установка Node.js для проверки
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3: проверка html с помощью html-proofer
      - name: Setup HTMLProofer
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full
          sudo gem install html-proofer
      - name: Check file structure
        run: |
          echo "Проверяем структуру проекта..."
          if [ ! -f "index.html" ]; then echo "ERROR: index.html not found!"; exit 1; fi
          echo "✓ Базовая структура в порядке"
        
      - name: Run HTMLProofer
        run: |
          htmlproofer . --checks html --disable-external --allow-hash-href
  notify-telegram:
    runs-on: ubuntu-latest
    needs: check_html
    if: always() # Всегда запускается, даже если предыдущий job упал
    name: Telegram Notification
    steps:
      - name: Send Telegram notification
        uses: appleboy/telegram-action@v0.1.0
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            🚀 CI/CD Статус
            --------------------------
            📁 Проект: ${{ github.repository }}
            🔖 Ветка: ${{ github.ref_name }}
            👤 Автор: ${{ github.actor }}
            --------------------------
            📊 Статус: ${{ job.status }}
            ✅ Тесты: ${{ needs.check_html.result }}
            --------------------------
            🔗 View Results: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            🌐 Live Site: my-portfolio-git-main-egors-projects-ec1924bf.vercel.app
          format: html
